ARG base_img=ubuntu:18.04
FROM ${base_img}
RUN apt update
RUN apt install -y bash-completion
RUN perl -i.orig -pe 's/^#// if $x;'\
' /^#\s*enable.*bash.*completion/ && do{$x=1};'\
' /^\s*$/ && do{$x=0}' /etc/bash.bashrc 
#
